# Generated by Django 5.2.4 on 2025-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('LANH_DAO_CO_QUAN', 'Lãnh đạo Cơ quan'), ('LANH_DAO_VAN_PHONG', 'Lãnh đạo Văn phòng'), ('LANH_DAO_PHONG', 'Lãnh đạo Phòng'), ('CHUYEN_VIEN_VAN_PHONG', 'Chuyên viên Văn phòng'), ('CHUYEN_VIEN_PHONG', 'Chuyên viên Phòng')], default='CHUYEN_VIEN_PHONG', max_length=50),
        ),
    ]
