# Generated by Django 5.2.4 on 2025-08-12 02:51

from django.db import migrations

def update_chuyenvien_role(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    # Update users with the old 'CHUYEN_VIEN' role to 'CHUYEN_VIEN_PHONG'
    CustomUser.objects.filter(role='CHUYEN_VIEN').update(role='CHUYEN_VIEN_PHONG')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.RunPython(update_chuyenvien_role),
    ]
