# Generated by Django 5.2.4 on 2025-08-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoQuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên báo cáo')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model nguồn')),
                ('fields_to_display', models.JSONField(verbose_name='Các trường hiển thị')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='Bộ lọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
            ],
        ),
        migrations.CreateModel(
            name='GiaiNgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên giải ngân')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('date', models.DateField(verbose_name='Ngày giải ngân')),
            ],
        ),
        migrations.CreateModel(
            name='GiaTriTruongDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Giá trị')),
            ],
        ),
        migrations.CreateModel(
            name='GoiThau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên gói thầu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.CreateModel(
            name='HoSoCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ho_so_cong_viec', models.CharField(max_length=255, verbose_name='Tên hồ sơ công việc')),
                ('ma_ho_so_cong_viec', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Mã hồ sơ công việc')),
                ('mo_ta', models.TextField(verbose_name='Mô tả')),
                ('trang_thai', models.CharField(choices=[('CHO_PHE_DUYET', 'Chờ phê duyệt'), ('DA_TU_CHOI', 'Đã từ chối'), ('DA_DUYET', 'Đã duyệt'), ('DANG_TRIEN_KHAI', 'Đang triển khai'), ('TAM_DUNG', 'Tạm dừng'), ('HOAN_THANH', 'Hoàn thành'), ('DA_LUU_TRU', 'Đã lưu trữ'), ('DA_HUY', 'Đã hủy')], default='CHO_PHE_DUYET', max_length=50, verbose_name='Trạng thái')),
                ('phan_loai_linh_vuc', models.CharField(max_length=255, verbose_name='Phân loại lĩnh vực')),
                ('can_cu_phap_ly', models.TextField(verbose_name='Căn cứ pháp lý')),
                ('ngay_bat_dau', models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc')),
            ],
        ),
        migrations.CreateModel(
            name='KeHoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ke_hoach', models.CharField(max_length=255, verbose_name='Tên kế hoạch')),
                ('muc_tieu', models.TextField(verbose_name='Mục tiêu')),
                ('trang_thai', models.CharField(choices=[('CHUA_BAT_DAU', 'Chưa bắt đầu'), ('DANG_THUC_HIEN', 'Đang thực hiện'), ('HOAN_THANH', 'Hoàn thành'), ('BI_TRE', 'Bị trễ'), ('DA_DUYET', 'Đã duyệt')], default='CHUA_BAT_DAU', max_length=50, verbose_name='Trạng thái')),
                ('thoi_gian_bat_dau', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(verbose_name='Thời gian kết thúc')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuCongViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mo_ta', models.CharField(max_length=255, null=True, verbose_name='Mô tả hành động')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Chi tiết')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoaiNhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên loại nhiệm vụ')),
            ],
        ),
        migrations.CreateModel(
            name='MocThoiGian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_moc', models.CharField(max_length=255, verbose_name='Tên mốc')),
                ('ngay_den_han', models.DateTimeField(verbose_name='Ngày đến hạn')),
                ('trang_thai', models.CharField(choices=[('CHUA_BAT_DAU', 'Chưa bắt đầu'), ('HOAN_THANH', 'Hoàn thành'), ('BI_TRE', 'Bị trễ')], default='CHUA_BAT_DAU', max_length=50, verbose_name='Trạng thái')),
            ],
        ),
        migrations.CreateModel(
            name='NhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhiem_vu', models.CharField(max_length=255, verbose_name='Tên nhiệm vụ')),
                ('mo_ta', models.TextField(verbose_name='Mô tả')),
                ('trang_thai', models.CharField(choices=[('PENDING_ASSIGNMENT_APPROVAL', 'Chờ duyệt giao'), ('ASSIGNED', 'Đã giao'), ('PENDING_COMPLETION_APPROVAL', 'Chờ duyệt hoàn thành'), ('COMPLETED', 'Hoàn thành')], default='PENDING_ASSIGNMENT_APPROVAL', max_length=50, verbose_name='Trạng thái')),
                ('muc_do_uu_tien', models.CharField(choices=[('KHAN', 'Khẩn'), ('CAO', 'Cao'), ('THUONG', 'Thường'), ('THAP', 'Thấp')], default='THUONG', max_length=50, verbose_name='Mức độ ưu tiên')),
                ('ngay_bat_dau', models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('thoi_gian_uoc_tinh', models.FloatField(blank=True, null=True, verbose_name='Thời gian ước tính (giờ)')),
                ('thoi_gian_thuc_te', models.FloatField(blank=True, null=True, verbose_name='Thời gian thực tế (giờ)')),
                ('thoi_gian_xu_ly', models.FloatField(blank=True, null=True, verbose_name='Thời gian xử lý (giờ)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Nhiệm vụ lặp lại')),
                ('recurring_frequency', models.CharField(blank=True, choices=[('DAILY', 'Hàng ngày'), ('WEEKLY', 'Hàng tuần'), ('MONTHLY', 'Hàng tháng'), ('YEARLY', 'Hàng năm')], max_length=20, null=True, verbose_name='Tần suất lặp lại')),
                ('recurring_until', models.DateTimeField(blank=True, null=True, verbose_name='Lặp lại đến ngày')),
                ('danh_gia_sao', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='Đánh giá sao')),
                ('loi_danh_gia', models.TextField(blank=True, null=True, verbose_name='Lời đánh giá')),
                ('ngay_ket_thuc_de_xuat', models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc đề xuất')),
                ('ly_do_gia_han', models.TextField(blank=True, null=True, verbose_name='Lý do gia hạn')),
                ('trang_thai_gia_han', models.CharField(choices=[('CHUA_DUYET', 'Chưa duyệt'), ('DA_DUYET', 'Đã duyệt'), ('DA_TU_CHOI', 'Đã từ chối')], default='CHUA_DUYET', max_length=50, verbose_name='Trạng thái gia hạn')),
                ('is_quy_trinh_dac_biet', models.BooleanField(default=False, verbose_name='Quy trình đặc biệt')),
                ('ngay_hoan_thanh', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TepDinhKem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='TruongDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên trường dữ liệu')),
                ('data_type', models.CharField(max_length=50, verbose_name='Kiểu dữ liệu')),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.binhluan')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
