# Generated by Django 5.2.4 on 2025-08-13 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='binhluan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customreport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='hosocongviec',
            name='id_nguoi_quan_ly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_an_quan_ly', to=settings.AUTH_USER_MODEL, verbose_name='Người quản lý'),
        ),
        migrations.AddField(
            model_name='goithau',
            name='ho_so_cong_viec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goi_thau', to='core.hosocongviec', verbose_name='Hồ sơ công việc'),
        ),
        migrations.AddField(
            model_name='giatritruongdulieu',
            name='ho_so_cong_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_truong_du_lieu', to='core.hosocongviec', verbose_name='Hồ sơ công việc'),
        ),
        migrations.AddField(
            model_name='giaingan',
            name='ho_so_cong_viec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giai_ngan', to='core.hosocongviec', verbose_name='Hồ sơ công việc'),
        ),
        migrations.AddField(
            model_name='kehoach',
            name='id_du_an',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ke_hoach', to='core.hosocongviec', verbose_name='Hồ sơ công việc'),
        ),
        migrations.AddField(
            model_name='kehoach',
            name='id_nguoi_phu_trach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ke_hoach_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Người phụ trách'),
        ),
        migrations.AddField(
            model_name='lichsucongviec',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mocthoigian',
            name='id_ke_hoach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moc_thoi_gian', to='core.kehoach', verbose_name='Kế hoạch'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_ke_hoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu', to='core.kehoach', verbose_name='Kế hoạch'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_duyet_giao_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_duyet_giao', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt giao việc'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_giao_viec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_giao', to=settings.AUTH_USER_MODEL, verbose_name='Người giao việc'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_xu_ly_chinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_xu_ly_chinh', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý chính'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nhiem_vu_cha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tasks', to='core.nhiemvu', verbose_name='Nhiệm vụ cha'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='nguoi_dong_xu_ly',
            field=models.ManyToManyField(blank=True, related_name='nhiem_vu_dong_xu_ly', to=settings.AUTH_USER_MODEL, verbose_name='Người đồng xử lý'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='nguoi_duyet_gia_han',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_duyet_gia_han', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt gia hạn'),
        ),
        migrations.AddField(
            model_name='lichsucongviec',
            name='nhiem_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='core.nhiemvu'),
        ),
        migrations.AddField(
            model_name='giatritruongdulieu',
            name='nhiem_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_truong_du_lieu', to='core.nhiemvu', verbose_name='Nhiệm vụ'),
        ),
        migrations.AddField(
            model_name='binhluan',
            name='nhiem_vu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='binh_luan', to='core.nhiemvu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_ho_so_cong_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hosocongviec'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhiemvu'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phongban',
            name='co_quan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coquan'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_phong_ban_lien_quan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phongban', verbose_name='Phòng ban liên quan'),
        ),
        migrations.AddField(
            model_name='kehoach',
            name='id_don_vi_thuc_hien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phongban', verbose_name='Đơn vị thực hiện'),
        ),
        migrations.AddField(
            model_name='hosocongviec',
            name='id_don_vi_chu_tri',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phongban', verbose_name='Đơn vị chủ trì'),
        ),
        migrations.AddField(
            model_name='tepdinhkem',
            name='binh_luan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='core.binhluan'),
        ),
        migrations.AddField(
            model_name='tepdinhkem',
            name='ho_so_cong_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='core.hosocongviec'),
        ),
        migrations.AddField(
            model_name='tepdinhkem',
            name='ke_hoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='core.kehoach'),
        ),
        migrations.AddField(
            model_name='tepdinhkem',
            name='nhiem_vu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='core.nhiemvu'),
        ),
        migrations.AddField(
            model_name='tepdinhkem',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='giatritruongdulieu',
            name='truong_du_lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truongdulieu', verbose_name='Trường dữ liệu'),
        ),
    ]
