# Generated by Django 5.2.4 on 2025-08-10 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiNhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên loại nhiệm vụ')),
            ],
        ),
        migrations.CreateModel(
            name='TruongDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên trường dữ liệu')),
                ('data_type', models.CharField(max_length=50, verbose_name='Kiểu dữ liệu')),
            ],
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_giao_viec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_giao', to=settings.AUTH_USER_MODEL, verbose_name='Người giao việc'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_tao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_phong_ban_lien_quan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.phongban', verbose_name='Phòng ban liên quan'),
        ),
        migrations.AlterField(
            model_name='nhiemvu',
            name='trang_thai',
            field=models.CharField(choices=[('PENDING_ASSIGNMENT_APPROVAL', 'Chờ duyệt giao'), ('ASSIGNED', 'Đã giao'), ('PENDING_COMPLETION_APPROVAL', 'Chờ duyệt hoàn thành'), ('COMPLETED', 'Hoàn thành')], default='PENDING_ASSIGNMENT_APPROVAL', max_length=50, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='GiaiNgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên giải ngân')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('date', models.DateField(verbose_name='Ngày giải ngân')),
                ('ho_so_cong_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giai_ngan', to='core.hosocongviec', verbose_name='Hồ sơ công việc')),
            ],
        ),
        migrations.CreateModel(
            name='GoiThau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên gói thầu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('ho_so_cong_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goi_thau', to='core.hosocongviec', verbose_name='Hồ sơ công việc')),
            ],
        ),
        migrations.CreateModel(
            name='GiaTriTruongDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Giá trị')),
                ('ho_so_cong_viec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_truong_du_lieu', to='core.hosocongviec', verbose_name='Hồ sơ công việc')),
                ('nhiem_vu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gia_tri_truong_du_lieu', to='core.nhiemvu', verbose_name='Nhiệm vụ')),
                ('truong_du_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.truongdulieu', verbose_name='Trường dữ liệu')),
            ],
        ),
    ]
