# Generated by Django 5.2.4 on 2025-08-10 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loainhiemvu_truongdulieu_nhiemvu_id_nguoi_giao_viec_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nhiemvu',
            name='ly_do_gia_han',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do gia hạn'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='ngay_ket_thuc_de_xuat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc đề xuất'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='nguoi_duyet_gia_han',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_duyet_gia_han', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt gia hạn'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='trang_thai_gia_han',
            field=models.CharField(choices=[('CHUA_DUYET', 'Chưa duyệt'), ('DA_DUYET', 'Đã duyệt'), ('DA_TU_CHOI', 'Đã từ chối')], default='CHUA_DUYET', max_length=50, verbose_name='Trạng thái gia hạn'),
        ),
    ]
