# Generated by Django 5.2.4 on 2025-08-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nhiemvu_id_nguoi_duyet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosocongviec',
            name='id_nguoi_quan_ly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='du_an_quan_ly', to=settings.AUTH_USER_MODEL, verbose_name='LĐ theo dõi'),
        ),
        migrations.AlterField(
            model_name='kehoach',
            name='id_nguoi_phu_trach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ke_hoach_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='LĐ theo dõi'),
        ),
    ]
