# Generated by Django 5.2.4 on 2025-08-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nhiemvu_ly_do_gia_han_nhiemvu_ngay_ket_thuc_de_xuat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhiemvu',
            name='id_ke_hoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu', to='core.kehoach', verbose_name='Kế hoạch'),
        ),
    ]
