# Generated by Django 5.2.4 on 2025-08-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_hosocongviec_id_nguoi_quan_ly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kehoach',
            name='don_vi_phoi_hop',
            field=models.ManyToManyField(blank=True, related_name='ke_hoach_phoi_hop', to='core.phongban', verbose_name='Đơn vị phối hợp'),
        ),
    ]
