# Generated by Django 5.2.4 on 2025-08-10 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_nhiemvu_id_ke_hoach'),
    ]

    operations = [
        migrations.AddField(
            model_name='tepdinhkem',
            name='ke_hoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='core.kehoach'),
        ),
    ]
