# Generated by Django 4.2.23 on 2025-08-22 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_nhiemvu_nguoi_dong_xu_ly'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhiemvu',
            name='nguoi_dong_xu_ly',
            field=models.ManyToManyField(blank=True, related_name='nhiem_vu_dong_xu_ly', to=settings.AUTH_USER_MODEL, verbose_name='Người đồng xử lý'),
        ),
    ]
