# Generated by Django 5.2.4 on 2025-08-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tepdinhkem_ke_hoach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_duyet_giao_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_da_duyet_giao', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt giao việc'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='is_quy_trinh_dac_biet',
            field=models.BooleanField(default=False, verbose_name='Quy trình đặc biệt'),
        ),
    ]
