# Generated by Django 5.2.4 on 2025-08-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nhiemvu_id_nguoi_duyet_giao_viec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhiemvu',
            name='ngay_hoan_thanh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành'),
        ),
    ]
