# Generated by Django 5.2.4 on 2025-08-12 02:54

from django.db import migrations

def migrate_assignee_to_main_assignee(apps, schema_editor):
    NhiemVu = apps.get_model('core', 'NhiemVu')
    for nhiemvu in NhiemVu.objects.all():
        if hasattr(nhiemvu, 'id_nguoi_thuc_hien') and nhiemvu.id_nguoi_thuc_hien:
            nhiemvu.id_nguoi_xu_ly_chinh = nhiemvu.id_nguoi_thuc_hien
            nhiemvu.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nhiemvu_ngay_hoan_thanh'),
    ]

    operations = [
        migrations.RunPython(migrate_assignee_to_main_assignee),
    ]
