# Generated by Django 5.2.4 on 2025-08-12 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_nhiemvu_assignee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhiemvu',
            name='id_nguoi_thuc_hien',
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='id_nguoi_xu_ly_chinh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhiem_vu_xu_ly_chinh', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý chính'),
        ),
        migrations.AddField(
            model_name='nhiemvu',
            name='nguoi_dong_xu_ly',
            field=models.ManyToManyField(blank=True, related_name='nhiem_vu_dong_xu_ly', to=settings.AUTH_USER_MODEL, verbose_name='Người đồng xử lý'),
        ),
    ]
